### ISSUE TITLE
using namespace std and templates

### ISSUE THREAD

**Issue by stefan-gavranovic** [QuantStack/xeus-cling#102]
Error occurs when inserting `using namespace std;` in front of template definition.

```c++
#include <iostream>

using namespace std;

template<class T>
class Base
{
        
};
```
```bash
error: expected expression
template<class T>
^
```
when `using namespace std;` is removed there is no more error.

**Comment by JohanMabille** [comment]
can you try declaring your class in a different cell than the one used for the using statement?

**Comment by stefan-gavranovic** [comment]
That I tried out and it was working. But question is what is the problem with declaring it in the same cell?

**Comment by SylvainCorlay** [comment]
It is actually bug in cling (upstream), a lot of these can be solved by splitting the content of cells.

**Comment by stefan-gavranovic** [comment]
Ok thanks, good to know.
