### ISSUE TITLE
updating xeus-cling on anaconda?

### ISSUE THREAD

**Issue by rsokl** [QuantStack/xeus-cling#106]
It appears that xeus-cling 0.7.1 is still the latest version available via `conda`. Any plans to make 0.1 available soon?

This project rocks, by the way :)

**Comment by SylvainCorlay** [comment]
It seems that the version is 0.1 everywhere.

**Comment by rsokl** [comment]
Ah. My mistake. It turns out that `conda update` doesn't find the latest version of xeus-cling.  

`conda install xeus-cling=0.1 -c QuantStack -c condaforge` did the trick. Not sure why updating didn't work.

**Comment by SylvainCorlay** [comment]
👍
