### ISSUE TITLE
Linking to other libraries

### ISSUE THREAD

**Issue by hamzamerzic** [QuantStack/xeus-cling#107]
Hi. First of thank you for this great tool! I find it extremely useful for quick C++ prototyping and concisely presenting the results - something that I always found lacking when it comes to C++.

Now, I would also like to be able to link to other libraries - in my case Eigen and Boost, or even some custom made libraries. Is that possible? If so, could you please outline the steps how to do this? 

Thank you!

**Comment by gouarin** [comment]
@hamzamerzic thanks for your message.

You can link with other libraries using these two lines in a code cell

```
#pragma cling add_library_path(PATH_TO_YOUR_LIB)
#pragma cling load("libfoo")
```

**Comment by hamzamerzic** [comment]
Thanks for the quick reply @gouarin. Eigen is a header only library. In my case the path of Eigen is: `/usr/include/eigen3`, and I usually include the header with:

```c++
#include <Eigen/Dense>
```

When I tried:

```c++
#pragma cling add_library_path("/usr/include/eigen3")
#pragma cling load("Eigen/Dense")
```

it did not work. When I just did:

```c++
#pragma cling load("/usr/include/eigen3/Eigen/Dense")
```

this seemed to work. Is there a directive that I could use in such a way that it just adds the path to the `include`, so that I can do `$include <Eigen/Dense>` later on?

Also, could you point me to location of these directives? I would like to see what other options are offered. Thank you in advance!

**Comment by wolfv** [comment]
Hi Hamza :wave: good to see you here!

**Comment by SylvainCorlay** [comment]
@hamzamerzic you can check out some alternatives to Eigen in the context of the C++ kernel [here](https://beta.mybinder.org/v2/gh/QuantStack/xtensor/0.15.1-binder?filepath=notebooks/xtensor.ipynb).

Check out the numpy to xtensor cheat sheet. http://xtensor.readthedocs.io/en/latest/numpy.html
