### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Miguel-Manzo** [QuantStack/xeus-cling#110]
Hello! 
I followed the installation instructions in the README and I also verified that I had the appropriate dependencies installed according to the table posted at the end of the README file. Everything looks fine.

Then, I opened Jupyter and created a notebook selecting xeus-C++14 from the drop-down menu, but as soon as the notebook opens and the Kernel is initialized, a pop-up window is shown with the message: xeus-cling.exe has stopped working, and I can't do anything else.

In the console, it  generates the following Error:

ERROR in cling::CIFactory::createCI(): 
resource directory C:/bld/xeus-cling_1517845693970/_b_env/Library\lib\clang\5.0.0 not found!
input_line_1:1:10: fatal error: 'new' file not found
#include <new>

I read that by December 2017 you were working on Xeus-cling for Windows and that you were solving some issues... I couldn't find if you solved them or not, and if Xeus-cling is working fine in Windows now.

Is this one of this issues? Do you know a way to solve it?

Thanks!

**Comment by liudonghua123** [comment]
I have the similar problem.

The error log on console is 

```
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1520449279312/_b_env/Library\lib\clang\5.0.0 not found!
```

**Comment by liudonghua123** [comment]
If I choose C++ 11, I could do nothing.

![image](https://user-images.githubusercontent.com/2276718/37266122-3203e172-25f3-11e8-83a3-38e5636b1910.png)

The error message on console is the following.

```
C:\Users\Liu.D.H>jupyter notebook
[I 12:44:10.580 NotebookApp] Serving notebooks from local directory: C:\Users\Liu.D.H
[I 12:44:10.580 NotebookApp] 0 active kernels
[I 12:44:10.581 NotebookApp] The Jupyter Notebook is running at:
[I 12:44:10.582 NotebookApp] http://localhost:8888/?token=9f6c48b714962995032465e8249f6e9fdfccf11b5c5556e6
[I 12:44:10.584 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:44:10.591 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=9f6c48b714962995032465e8249f6e9fdfccf11b5c5556e6
[I 12:44:10.779 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 12:44:19.177 NotebookApp] Saving file at /C_notebooks/Untitled.ipynb
[W 12:44:19.931 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20180312124409 (::1) 10.01ms referer=http://localhost:8888/notebooks/C_notebooks/Untitled.ipynb
[I 12:44:20.138 NotebookApp] Kernel started: c737828c-5ce3-4b78-afd0-19ab12f7dad1
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1520449279312/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\new:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\exception:7:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\type_traits:6:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include\xstddef:257:2: error: 'auto' return without trailing return type; deduced return types are a C++14 extension
        auto _Unfancy(_Ptrty _Ptr)
        ^
[W 12:44:30.152 NotebookApp] Timeout waiting for kernel_info reply from c737828c-5ce3-4b78-afd0-19ab12f7dad1
[I 12:44:32.113 NotebookApp] Interrupted...
[I 12:44:32.115 NotebookApp] Shutting down 1 kernel
[I 12:44:32.116 NotebookApp] Kernel shutdown: c737828c-5ce3-4b78-afd0-19ab12f7dad1

C:\Users\Liu.D.H>
```

**Comment by SylvainCorlay** [comment]
Hi @Miguel-Manzo @liudonghua123 unfortunately, the windows platform is not supported yet by cling.

We provide an experimental build as we are trying to resolve this situation eventually.

**Comment by punchEnbody** [comment]
I know it has been awhile and Windows isn't a priority, but I just did a fresh install using a new miniconda environment and the sample notebook in the repository still causes a problem "fatal error: 'new' file not found" marking #include<new> as the problem. 

Thanks for all the work you folks are doing!

**Comment by iroot** [comment]
There is an option to install xeus-cling in WSL.

**Comment by WesFrank** [comment]
> Yep, I guess that is the answer. I did the unix install under wsl and it works fine. When you start a notebook server you cannot directly connect to a browser from the wsl side (unless you start a browser in the wsl itself), but the server gives you a token you can paste into the windows-side browser and it all works great. Thanks for the suggestion.

Create a symbolic link and set up a bash script in wsl that links from a windows shortcut
https://envyen.com/posts/2021-06-27-C-CPP-Jupyter-Notebook-Windows/

**Comment by WesFrank** [comment]
> The token does not have to be copied every time, just do it once and then open http://localhost:8888/lab

@iROOT 

Here's a video of the above quoted reply @wfpunch https://www.youtube.com/watch?v=FubmUTaspDc
