### ISSUE TITLE
jupyter notebook call on fresh install via conda fails on MacOS 10.13.3

### ISSUE THREAD

**Issue by PrometheusPi** [QuantStack/xeus-cling#131]
I just recently installed anaconda on my Mac with MacOS 10.13.3 (Xcode installed) via:
```bash
curl https://repo.continuum.io/archive/Anaconda3-5.1.0-MacOSX-x86_64.sh -o Anaconda3-5.1.0-MacOSX-x86_64.sh 
bash Anaconda3-5.1.0-MacOSX-x86_64.sh 
# some interaction with the installer
# extend $PATH to contain anaconda path
```

From that, I followed the xeus instruction and created a virtuell environment for running a jupyter c++14 kernel as described [in the README.md](https://github.com/QuantStack/xeus-cling/blob/master/README.md)

```bash
conda create -n cling
source activate cling
conda install xeus-cling notebook -c QuantStack -c conda-forge
```

There were no errors during installation of the required packages. 

However, when running `jupyter notebook` the following error occured:
```bash
Traceback (most recent call last):
  File "/Users/.../anaconda3/envs/cling/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/.../anaconda3/envs/cling/lib/python3.6/site-packages/notebook/notebookapp.py", line 45, in <module>
    ioloop.install()
  File "/Users/.../anaconda3/envs/cling/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 210, in install
    assert (not ioloop.IOLoop.initialized()) or \
AttributeError: type object 'IOLoop' has no attribute 'initialized'
```

What might cause this error? This is a freshly installed OS and a newly created user. There should be no side effects.

Is the install script for some reason assuming the the anaconda path extension is in `.bash_profile`? Because I extend the `PATH` manually. 
Is xeus not working with specific jupyter settings as no browser, password etc.?

In a python only virtuell environment, `jupyter notebook` runs fine.

**Comment by gouarin** [comment]
@PrometheusPi it seems a tornado version problem.

Could you tell us what is the version of tornado using the command line

```
conda list
```

If the version is `5`, you need to downgrade it to `4.5`.

**Comment by PrometheusPi** [comment]
@gouarin Thank you for the fast reply.
The original version of tornado was `5.0.1`. Downgrading to `4.5.3` resolved the issue. 
Thanks a lot for this advice.

**Comment by ax3l** [comment]
Nice, I hit the same issue and solved it via
```bash
conda install "tornado<5.0.0"
```
as well.

**Comment by SylvainCorlay** [comment]
cf https://github.com/conda-forge/notebook-feedstock/issues/31#issuecomment-376811574

We should upgrade QuantStack's pyzmq.

**Comment by PrometheusPi** [comment]
@ax3l So it is not just related to the MacOS version of anaconda. I will update the title of the issue. Thanks.
