### ISSUE TITLE
nlohmann_json 3.1.2 md5 mismatch

### ISSUE THREAD

**Issue by madhavajay** [QuantStack/xeus-cling#153]
When following the README instructions:

```
$ conda install xeus-cling notebook -c QuantStack -c conda-forge
```

I get the following error:
Downloading and Extracting Packages
nlohmann_json 3.1.2#######################################7              |  75%

MD5MismatchError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/QuantStack/osx-64/nlohmann_json-3.1.2-0.tar.bz2'.
  download saved to: /usr/local/miniconda3/pkgs/nlohmann_json-3.1.2-0.tar.bz2
  expected md5 sum: 94c102fc52a15e4f7db27402c4a23a1f
  actual md5 sum: e972965b941107a1a0ed69c95ccc50d2

**Comment by madhavajay** [comment]
A work around was to install an older version first:
```
$ conda install nlohmann_json=3.1.1 -c QuantStack
```

**Comment by SylvainCorlay** [comment]
Thanks for reporting. It looks like a bug in conda. I will drop the nlohmann_json 3.1.2 and rebuild it when I am close to a keyboard.

**Comment by SylvainCorlay** [comment]
@madhavajay I have uploaded a new build for the nlohmann_json package on OS X, which should solve this.

Closing the issue, but feel free to report it here if anything else comes up!

Thanks

**Comment by madhavajay** [comment]
Cool, I installed it and it works! 😄
