### ISSUE TITLE
conda install failed on ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by congzhangzh** [QuantStack/xeus-cling#158]
I try to install by minconda with:

conda env create --file=xeus-cling/environment.ymll

it will failed!

after I fork and try to start notebook in new forked repo xeus-cling/notebooks/xcpp.ipynb from mybinder, it will failed too.

I do not know why your version loader from binder will successful sometimes.

Can you have a try and confirm that conda env will reproduceable from you yml file?

**Comment by SylvainCorlay** [comment]
Hello, can you please report the error messages that you are seeing?

**Comment by SylvainCorlay** [comment]
This appears to be fixed now!

Closing the issue but if you encounter it again, I will reopen.
