### ISSUE TITLE
Passing arguments to the cling interpreter 

### ISSUE THREAD

**Issue by SimeonEhrig** [QuantStack/xeus-cling#159]
I try to pass arguments to the cling interpreter instance for example to use OpenMP in my notebook.

The bash command would be:
```bash
cling -fopenmp
```

In the main.cpp, I see it is not possible to pass arguments via `argv` in the `kernel.json`
https://github.com/QuantStack/xeus-cling/blob/ee531ff81c9eef10067e650e3f5668a1d41db288/src/main.cpp#L46-L58

Is there any way to pass arguments to the cling interpreter? For example, the jupyter kernel of the cling project use an environment variable.
https://github.com/root-project/cling/commit/6bbf1f331185ce9b6c0bfe236e687e62112ad747

**Comment by SylvainCorlay** [comment]
Thanks for opening the issue. I agree that we should probably support this feature, probably with some options parsing utility.

Tagging as a feature request.

**Comment by SimeonEhrig** [comment]
I implemented a solution based on the cling jupyter solution. See Pull Request #169

**Comment by SimeonEhrig** [comment]
Solved in Pull Request #169
