### ISSUE TITLE
Language info version

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xeus-cling#172]
The last release introduced a regression (or at least a change in behavior) in the kernel info: the language info version changed from `14` to `-std=c++14`.

**Comment by takluyver** [comment]
I don't think there's any expected format, and I don't think any code uses it at present. If anything does use it, I'd guess it will be for estimating how compatible an available kernel is with some specified metadata. I'd recommend sticking to a numeric version like `14` if that's practical - this is the easiest for things to make sense of as a version.
