### ISSUE TITLE
Xeus-cling does not read any input

### ISSUE THREAD

**Issue by sesh1989** [QuantStack/xeus-cling#175]
I am using xeus-cling kernel downloaded last week (Jul-27-2018) on MacOS High Sierra. I attempted to run the following program in a C++17 kernel:
````
#include <string>
#include <iostream>
using namespace std;

char text[256], num[20];
cout << "Type any number";
cin.getline(num, 20);
cout << "Type your name";
cin.getline(text, 256);
cout << num << ", " << text;
````
When I ran the program, I got the following output instantly. Obviously, it did not wait for any keyboard input from me.

`Type any numberType your name, `

**Comment by SylvainCorlay** [comment]
The master branch now supports input requests as of #206.

This should be included in the next release.

**Comment by sesh1989** [comment]
Thanks. Verified that the new new version displays proper behavior.
