### ISSUE TITLE
/usr/bin/ld: cannot find -lcryptopp

### ISSUE THREAD

**Issue by yurivict** [QuantStack/xeus-cling#182]
The ```cryptopp``` dependency comes through ```xeus```. The library ```/usr/local/lib/libcryptopp.so``` exists. It appears that the path ```-L/usr/local/lib``` isn't provided to ```ld```.

**Comment by SylvainCorlay** [comment]
@yurivict if you build xeus from source, you need to use the `cryptopp-cmake` that is the cmake-enabled cryptopp. Unfortunately, they dropped the cmake support upstream.

**Comment by yurivict** [comment]
```cryptopp-cmake``` didn't work when I tried it.

**Comment by SylvainCorlay** [comment]
This is what we use to package cryptopp on conda. You can check out the conda-forge recipe for cryptopp.

**Comment by yurivict** [comment]
I just tried again, it's still broken: https://github.com/noloader/cryptopp-cmake/issues/45
Another bug is also still unresolved: https://github.com/noloader/cryptopp-cmake/issues/34

**Comment by SylvainCorlay** [comment]
> noloader/cryptopp-cmake#34

Can you provide some details on how you built cryptopp-cmake. In our experience, the cmake files are properly generated.

**Comment by yurivict** [comment]
The new version doesn't have this problem any more.

Thank you for helping!
