### ISSUE TITLE
error: use of overloaded operator '<<' is ambiguous

### ISSUE THREAD

**Issue by dmgoldschmidt** [QuantStack/xeus-cling#186]

**Comment by dmgoldschmidt** [comment]
Hit return too early.  Here's the cell:
#include \<iostream\>
using namespace std;
double a = 1;
double b = 2;
cout <<"a: "<<a<<" b: "<<b<<endl;

input_line_28:5:14: error: use of overloaded operator '<<' is ambiguous (with operand types 'basic_ostream<char,
      std::char_traits<char> >' and 'double')
cout << "a: "<<a<<" b: "<<b<<endl;
~~~~~~~~~~~~~^ ~

**Comment by srpgilles** [comment]
You should try restarting your kernel, and if this doesn't work update your Xeus-cling installation: I tried your example and it worked perfectly fine.
