### ISSUE TITLE
error when building xeus from source

### ISSUE THREAD

**Issue by pankajkumar229** [QuantStack/xeus-cling#201]
I am not sure what the error is here. I have conda path in $your_conda_path and I have llvm/cling installed from sources.

```
osboxes@kubserver:~/work/xeus-cling$ cmake -DCMAKE_INSTALL_PREFIX=$your_conda_path -DCMAKE_INSTALL_LIBDIR=$your_conda_path/lib
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building xeus-cling v0.4.8
-- Found LLVM_CONFIG as /home/osboxes/cling/cling-install/bin/llvm-config
CMake Error at CMakeLists.txt:104 (find_package):
  By not providing "Findxeus.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "xeus", but
  CMake did not find one.

  Could not find a package configuration file provided by "xeus" (requested
  version 0.15.0) with any of the following names:

    xeusConfig.cmake
    xeus-config.cmake

  Add the installation prefix of "xeus" to CMAKE_PREFIX_PATH or set
  "xeus_DIR" to a directory containing one of the above files.  If "xeus"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/osboxes/work/xeus-cling/CMakeFiles/CMakeOutput.log".
```

**Comment by SylvainCorlay** [comment]
You seem to be missing xeus which is a requirement to xeus-cling.

**Comment by SylvainCorlay** [comment]
Closing!

**Comment by greatlse** [comment]
I met the same problem, and I installed xues

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building xeus-cling v0.5.1
-- Found LLVM_CONFIG as D:/program/ontinuum/anaconda3/Library/bin/llvm-config.ex
e
CMake Error at CMakeLists.txt:107 (find_package):
  Could not find a configuration file for package "xeus" that is compatible
  with requested version "0.19.0".

  The following configuration files were considered but not accepted:

    D:/program/ontinuum/anaconda3/pkgs/xeus-0.19.0-h1ad3211_1/Library/lib/cmake/
xeus/xeusConfig.cmake, version: 0.19.0 (64bit)
    D:/program/ontinuum/anaconda3/Library/lib/cmake/xeus/xeusConfig.cmake, versi
on: 0.19.0 (64bit)



-- Configuring incomplete, errors occurred!
See also "D:/program/xeus-cling-0.5.1/build/CMakeFiles/CMakeOutput.log".
