### ISSUE TITLE
Could 3D API work ?

### ISSUE THREAD

**Issue by Sumenia** [QuantStack/xeus-cling#207]
Until recently I didn't know Jupiter Notebook could be working with something else than Python and I was not expecting it to be working with c++. It's impressive, good work !

I was wondering, maybe with some tweaks, if it could potentially work with 3D API such as OpenGL/Vulkan ? 🤔

**Comment by wolfv** [comment]
Hi Yoann, 

there are multiple levels on which that could work.
You can definitely use WebGL from C++ via the widgets, as done in xvolume (github.com/QuantStack/xvolume , based on ipyvolume)

Not sure how you'd go about a more native way to do this, though.

**Comment by SylvainCorlay** [comment]
@Sumenia you can try out the [xleaflet](https://mybinder.org/v2/gh/QuantStack/xleaflet/stable?filepath=notebooks) binder for an interactive visualization example. (This one is with maps).

A similar one is being worked on for 3-D plotting in the xvolume package, but still early-stage.
