### ISSUE TITLE
problem in activating xeus-cling in windows 10

### ISSUE THREAD

**Issue by IlanHindy** [QuantStack/xeus-cling#211]
Hi,
The C++ xeus-cling kernel fails.
I did the following:
Install a new Miniconda
Created a new conda env
Installed Jupiter
Installed xeus-cling with the command 👍 

> conda install xeus-cling notebook -c QuantStack -c conda-forge

The Jupiter notebook works with Python.
The C++ appears in the menu for possible kernels

I opened a conda terminal
activated the env
activated Jupyter with the command Jupyter notebook.

I get the following error (The kernel retally starts and fail)

> I 12:45:03.384 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
> WARNING:root:kernel ca5df96a-c6b5-41d9-aaa2-b496f6a51fc5 restarted
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> 2
> ERROR in cling::CIFactory::createCI():
>   resource directory C:/bld/xeus-cling_1544660831115/_b_env/Library\lib\clang\5.0.0 not found!
> input_line_1:1:10: fatal error: 'new' file not found
> #include <new>
>          ^~~~~
> Warning in cling::IncrementalParser::CheckABICompatibility():
>   Possible C++ standard library mismatch, compiled with _CRT_MSVCP_CURRENT 'msvcp140.dll'
>   Extraction of runtime standard library version was: ''
> [I 12:45:09.422 NotebookApp] Interrupted...
> [I 12:45:09.438 NotebookApp] Shutting down 1 kernel
> [I 12:45:09.438 NotebookApp] Kernel shutdown: ca5df96a-c6b5-41d9-aaa2-b496f6a51fc5  
> 

Can you tell me what is the problem?
Ilan

**Comment by SylvainCorlay** [comment]
We don't really support windows unfortunately. I recommend using linux or OS X.

**Comment by SalihKARAHAN** [comment]
> We don't really support windows unfortunately. I recommend using linux or OS X.

**WHY? **

**Comment by parangatm** [comment]
Is there any solution for this still?
