### ISSUE TITLE
C++ notebook does not appear in the new-dropdown

### ISSUE THREAD

**Issue by christianthilker** [QuantStack/xeus-cling#217]
Hello there!

Before starting, I deleted my anaconda installation and installed a fresh miniconda. I then ran the following commands as instructed in the README file:

`conda create -n cling`
`source activate cling`
`conda install xeus-cling -c conda-forge`

Then starting a Jupiter notebook, I am not able to find a C++ option in the New-dropdown?

Thank you very much in advance! :)

**Comment by SylvainCorlay** [comment]
You probably are running jupyter from another environment that is not aware of the C++ kernel.

You can try installing `notebook` in the cling environment and report if this solved your issue.

**Comment by christianthilker** [comment]
Thanks for the swift reply. I ran the following command
`conda install xeus-cling notebook -c QuantStack -c conda-forge`
which solved the problem. Thank you!

**Comment by gnithink** [comment]
> You probably are running jupyter from another environment that is not aware of the C++ kernel.
> 
> You can try installing `notebook` in the cling environment and report if this solved your issue.

This is the reason why I did not get it to work. You need to install jupyter notebook in your current activated environment.

**Comment by pythologist** [comment]
It worked. (#217)

**Comment by AntonioDaSilva** [comment]
Worked for me too!
