### ISSUE TITLE
Unable to link iTensor

### ISSUE THREAD

**Issue by jsf15** [QuantStack/xeus-cling#223]
Hello everyone,

I'm new to C++ and I wanted to start with xeus-cling to do some prototyping. I need to use the iTensor library but I've been unable to link using the steps at #87 .

ITensor is installed in the folder /home/my_name/itensor which contains: the headers (.h/.o/.cc files) inside a folder named "itensor"; a folder lib with .a files and other folder. Naturally if I request to load the headers

`#include "/home/my_name/itensor/itensor/all.h"`

it complains that a referenced header insider all.h is not found

>     'itensor/all_mps.h' file not found

Then I add the line `#pragma cling add_include_path("/home/my_folder/itensor/")` but to no avail... What I can do is to individually load every header using `#pragma cling load` but this not practical because this is an enormous library.

Could anyone help me? Thank you!

**Comment by wolfv** [comment]
You probably want to compile your library into one big shared object file? Is there a `.so` file somewhere?

**Comment by jsf15** [comment]
No `.so` file in sight. Should I create one?

**Comment by jsf15** [comment]
I got it to work, thanks for the suggestion of @wolfv !
For reference:
- When running make to install iTensor choose `ITENSOR_MAKE_DYLIB=1`to create a `.so`

- In the Jupyter notebook add
`#pragma cling add_include_path("/path/to/itensor/")`
`#pragma cling add_library_path("/path/to/itensor/lib")`
`#pragma cling load("libitensor.so")`
`#pragma cling load("libitensor-g.so")`
`#pragma cling load("/path/to/itensor/itensor/all_mps.h")`

**Comment by jsf15** [comment]
@
