### ISSUE TITLE
Is it compatible with arch linux ?

### ISSUE THREAD

**Issue by tbhaxor** [QuantStack/xeus-cling#233]

**Comment by SylvainCorlay** [comment]
To my knowledge, there is not specific reason why it would not be compatible with archlinux.

**Comment by tbhaxor** [comment]
I am trying to install it from [aur](https://aur.archlinux.org/packages/xeus/) and its exiting with error code 1

**Comment by tbhaxor** [comment]
this is an output of `$ yaourt -S xeus`

![image](https://user-images.githubusercontent.com/28386721/57537799-a691af00-7364-11e9-8c3c-c211ebf8a145.png)

and at last i got this
```
100 13593  100 13593    0     0   9426      0  0:00:01  0:00:01 --:--:--  9419
  -> Found Findcppzmq.cmake
  -> Found Findcryptopp.cmake
  -> Found FindZeroMQ.cmake
  -> Found package.patch
==> Validating source files with sha256sums...
    xeus-0.18.1.tar.gz ... Passed
    zmq_addon.hpp ... FAILED
    Findcppzmq.cmake ... Passed
    Findcryptopp.cmake ... Passed
    FindZeroMQ.cmake ... Passed
    package.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
==> ERROR: Makepkg was unable to build xeus.
==> Restart building xeus ? [y/N]
==> -----------------------------

```

**Comment by SylvainCorlay** [comment]
We are not the authors of the arch linux package, which was done by a third party. This appears to be an issue with the archlinux package.

**Comment by tbhaxor** [comment]
@SylvainCorlay  I got error while building from source

```
$ git clone https://github.com/QuantStack/xeus-cling.git
$ cd xeus-cling
$ mkdir build && cd build
$ cmake ..
```

![Uploading image.png…]()

**Comment by JohanMabille** [comment]
You need to install the dependencies (xeus, cling, all the dependencies of xeus). If the package of `xeus-cling` form your distrib does not work, we highly recommend to install `xeus-cling` with conda rather than from source.

**Comment by tbhaxor** [comment]
@JohanMabille  the native installation on arch linux fails so  i am using anaconda now
