### ISSUE TITLE
Updated to new clangdev

### ISSUE THREAD

**Issue by xuning97** [QuantStack/xeus-cling#238]
Any chance to update to newer version of clangdev or support newer verson of clangdev.

Some standard libraries has been change from experimental to standard, as we are using C++17, I cannot utilize Xeus-Cling to boost productivity.

**Comment by SylvainCorlay** [comment]
@xuning97 unfortunately, the pinning of clang comes from upstream (cling).

We are waiting on a cling release to improve the situation with respect to other upstream issues and windows support.

**Comment by SimeonEhrig** [comment]
There is already an issue at the cling repo: https://github.com/root-project/cling/issues/276
At the moment, the priority is not high enough that the developers want to update the Clan/llvm base. But, if there are enough people who want that, they will. This is the workflow of the root team. So please, add your interest to the issue. We also need a new version of the Clang/llvm base ;-)

**Comment by SylvainCorlay** [comment]
Closing as this is more an issue for cling core.
