### ISSUE TITLE
Using gnuplot with xeus-cling jupyter C++ kernal to import and plot .dat signal file

### ISSUE THREAD

**Issue by FarnamAdelkhani** [QuantStack/xeus-cling#239]
Working in Jupyter notebook with Xeus-cling C++ kernel, I'm trying to utilize Gnuplot to import a signal represented as a .dat file for the purpose of plotting. I just cannot get it to work. Does anyone have experience or advice here? If so, a short guide on how to get things working would be greatly appreciated.

**Comment by FarnamAdelkhani** [comment]
Works better on pc. Thank you

**Comment by SylvainCorlay** [comment]
@FarnamAdelkhani sorry for not replying earlier. I think that having an example of gnuplot working with xeus cling would be super nice. Let me know if you feel like sharing one.

**Comment by FarnamAdelkhani** [comment]
@SylvainCorlay No worries at all. Xeus-cling is fantastic and tremendously helpful to my workflow, I greatly appreciate you all. I'll see if I can come up with something, would indeed be a nice integration. I haven't had much luck with the gnuplot jupyter kernel project.

**Comment by arminms** [comment]
@FarnamAdelkhani @SylvainCorlay You can use [g3p](https://github.com/arminms/g3p) library that I've recently developed.
