### ISSUE TITLE
HTML Formatting in Notebook

### ISSUE THREAD

**Issue by vishwesh5** [QuantStack/xeus-cling#240]
Hi everyone

Is it possible to load HTML styling in a Xeus Cling kernel notebook? For example, I am doing something like this in python:

![image](https://user-images.githubusercontent.com/12136202/60243824-b5153500-98d6-11e9-9984-2cccde65c2c7.png)

Is there a Xeus Cling equivalent for this? Or is there a word around?

Thanks in advance

Vishwesh

**Comment by martinRenou** [comment]
I guess you could create your own HTML class, a bit like in the Notebook example with the image class: https://github.com/QuantStack/xeus-cling/blob/master/notebooks/xcpp.ipynb 

```c++
    struct html
    {   
        inline html(const std::string& value)
        {
            m_value = value;
        }
        
        std::string m_value;
    };
    
    xeus::xjson mime_bundle_repr(const html& h)
    {
        auto bundle = xeus::xjson::object();
        bundle["text/html"] = h.m_value;
        return bundle;
    }
```

That could be a first option. Another option could be to use https://github.com/QuantStack/xwidgets, it has an `html` widget class (https://github.com/QuantStack/xwidgets/blob/master/include/xwidgets/xhtml.hpp), that would be a more "dynamic" option.

**Comment by vishwesh5** [comment]
Thanks @martinRenou ! By any chance, is there an example for xhtml?

**Comment by martinRenou** [comment]
Yes! In this Notebook: https://github.com/QuantStack/xwidgets/blob/master/notebooks/xwidgets.ipynb if you look for HTML on the page you will see it

**Comment by vishwesh5** [comment]
This worked! 
![image](https://user-images.githubusercontent.com/12136202/60246788-14764380-98dd-11e9-9ee1-ecb5709ed350.png)

Thanks a lot!

One final question. In the image, I had to write the entire html styling code. Is it possible to load it from a file? My plan is to maintain a central styling file which can be loaded by all the c++ notebooks.

**Comment by martinRenou** [comment]
Maybe look for ways to load a file into an `std::string`, something like https://stackoverflow.com/questions/2602013/read-whole-ascii-file-into-c-stdstring

**Comment by vishwesh5** [comment]
Thanks for the reference! I was able to load the html style in a string `buffer.str()`

![image](https://user-images.githubusercontent.com/12136202/60247472-59e74080-98de-11e9-9c64-468f6c96c4fa.png)

Then I did this:

![image](https://user-images.githubusercontent.com/12136202/60247479-5fdd2180-98de-11e9-92cd-1673a617ca7d.png)

Am I missing something? I am pretty sure I am

**Comment by martinRenou** [comment]
I am not sure `xhtml(` at the beginning and `)xhtml` at the end are needed, can you try removing them?

**Comment by vishwesh5** [comment]
You are amazing! It worked! 

Thanks a lot for your help!

**Comment by martinRenou** [comment]
Ahah, happy to help :) I'm closing this. Don't hesitate to ask other questions though.
