### ISSUE TITLE
Error on OSX 10.12.6

### ISSUE THREAD

**Issue by filippo82** [QuantStack/xeus-cling#248]
Dear all,

I've installed `xeus-cling` following your instructions (with a newly installed miniconda) but I get these errors after opening a notebook and selecting the C++14 (same for 17) kernel:

`[I 10:59:51.553 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
ERROR in cling::CIFactory::createCI(): cannot extract standard library include paths!
Invoking:
  LC_ALL=C clang-4.0  -O3 -DNDEBUG -xc++ -E -v /dev/null 2>&1 >/dev/null | awk '/^#include </,/^End of search/{if (!/^#include </ && !/^End of search/){ print }}' | GREP_OPTIONS= grep -E "(c|g)\+\+"
Results was:
With exit code 256
ERROR in cling::CIFactory::createCI():
  resource directory /Users/filippo/miniconda3/envs/cling/lib/clang/5.0.0 not found!
input_line_1:1:10: fatal error: 'new' file not found
#include <new>
         ^~~~~
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with _LIBCPP_VERSION '4000'
  Extraction of runtime standard library version was: ''
[W 10:59:54.569 NotebookApp] KernelRestarter: restart failed
[W 10:59:54.569 NotebookApp] Kernel d15e5411-6220-4b1c-86cb-d55b43ff85c6 died, removing from map.`

Any help would be appreciated.
Thanks.

**Comment by JohanMabille** [comment]
Hi,

The package `xeus-cling 0.6.0` from conda-forge is broken. We are waiting for conda-forge maintainers to flag it as broken, then we will rebuild it. In the meantime, can you try with `xeus-cling 0.5.0` ?

**Comment by filippo82** [comment]
Hi Johan,

I have downgraded the package (`conda install -c conda-forge xeus-cling=0.5.0`) and now it works.

Thank you.
