### ISSUE TITLE
Error while using Xeus Cling with Libtorch

### ISSUE THREAD

**Issue by krshrimali** [QuantStack/xeus-cling#262]
Hi

I have set up `Xeus-Cling` to use with `Libtorch` and am getting error mentioned below while executing:

```cpp
#include <torch/csrc/autograd/variable.h>
#include <torch/csrc/autograd/function.h>

torch::Tensor a_tensor = torch::ones({2, 2}, torch::requires_grad());
torch::Tensor b_tensor = torch::randn({2, 2});

std::cout << a_tensor << std::endl;
std::cout << b_tensor << std::endl;

auto c_tensor = a_tensor + b_tensor;
c_tensor.backward(); // a.grad() will now hold the gradient of c w.r.t a

std::cout << c_tensor << std::endl;
```

Error:
```
IncrementalExecutor::executeFunction: symbol '__emutls_v._ZSt11__once_call' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!
IncrementalExecutor::executeFunction: symbol '__emutls_v._ZSt15__once_callable' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!
IncrementalExecutor::executeFunction: symbol '_ZN3c105ErrorC1ENS_14SourceLocationERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!
You are probably missing the definition of c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN3c106Symbol14fromQualStringERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!
You are probably missing the definition of c10::Symbol::fromQualString(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
Maybe you need to load the corresponding shared library?
```

Not sure what has gone wrong. System Configuration: Ubuntu 16.04, c++ (GCC) 7.2.0

Does anyone have an idea on this?

Thanks!

**Comment by krshrimali** [comment]
Acknowledging the fact that I was able to solve it by building PyTorch from the source.

Thanks!

**Comment by cauachagas** [comment]
It's possible with pytorch 1.1.0. [See here](https://github.com/cauachagas/cling-torch) (In portuguese, sorry)

Create an environment

```c++
conda env create -n cling-torch
source activate cling-torch
conda install xeus-cling notebook pytorch-cpu nb_conda_kernels -c conda-forge
```
Create a Notebook (kernell from cling-torch)

In First Cell 

```c++
#pragma cling add_include_path("$CONDA_PREFIX/lib/python3.7/site-packages/torch/include")
#pragma cling add_include_path("$CONDA_PREFIX/lib/python3.7/site-packages/torch/include/torch/csrc/api/include")
#pragma cling add_library_path("$CONDA_PREFIX/lib/python3.7/site-packages/torch/lib")
#pragma cling load("libtorch")
```

![image](https://user-images.githubusercontent.com/26585248/72260953-a849fb80-35f2-11ea-96da-0e86a410ded7.png)

**Comment by justinblaber** [comment]
![image](https://i.imgur.com/tuou7Hx.png)

I've built libtorch from scratch various different ways... Always get the same error.

**Comment by embededAI** [comment]
I met the same issue, torch::from_blob works fine in pure c++ code with libtorch, but if I call torch::from_blob in jupyter notebook with xeus-cling, the link error appear:

IncrementalExecutor::executeFunction: symbol '__emutls_v._ZSt11__once_call' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!
IncrementalExecutor::executeFunction: symbol '__emutls_v._ZSt15__once_callable' unresolved while linking function '_GLOBAL__sub_I_cling_module_8'!

https://discuss.pytorch.org/t/libtorch-on-jupyter-using-cling-c/54606 also mention this link error, but by now there is no solution...
