### ISSUE TITLE
Followed all instructions, everything seemed to work, but no C++ option

### ISSUE THREAD

**Issue by gcallah** [QuantStack/xeus-cling#263]
"Launch the jupyter notebook with jupyter notebook and launch a new C++ notebook by selecting the C++14 kernel in the new dropdown."

I got up to here successfully, but when I launch jupyter, no C++ option appears under New.

**Comment by martinRenou** [comment]
How did you install the kernel? Are you sure you installed it in the same environment as the Jupyter you are using?

**Comment by AdebayoBraimah** [comment]
Hi @gcallah and @martinRenou. Has any headway been made on this issue? I am also running into the same problem. I follow the instructions exactly, and launched a jupyter notebook from within the cling environment, but there is no C++ kernel available.

**Comment by AdebayoBraimah** [comment]
Hi @gcallah and @martinRenou. This worked for me on linux after following the directions from this closed ticket: https://github.com/QuantStack/xeus-cling/issues/256

```conda create -n cling python=3.7.3
conda activate cling
conda install jupyter xeus-cling -c conda-forge```

**Comment by martinRenou** [comment]
The QuantStack channel is not used anymore and will be deleted very soon. You should install everything from the conda-forge channel

**Comment by AdebayoBraimah** [comment]
@martinRenou dose this imply that windows will no longer be supported?

**Comment by gcallah** [comment]
I did the install just like the instructions said. I apologize, but I have not had time to try anything suggested yet, but I probably will do today

**Comment by martinRenou** [comment]
Sorry I did not see you were on Windows.

@SylvainCorlay do we support Windows? According to the README:
> The build for the Windows platform made available on our channel is merely experimental

I wonder if it's still a thing, and if cling will soon support Windows.

**Comment by SylvainCorlay** [comment]
No we have never supported windows.

However, with the latest release of cling, it will soon be possible.

**Comment by AdebayoBraimah** [comment]
Understood. Thanks @martinRenou and @SylvainCorlay for providing clarification.

**Comment by RemKamal** [comment]
Hello all,
I have never tried xeus-cling and now I work under Windows 10 system. After try and cry the installation was completed:

(cling) C:\>conda install xeus-cling -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: /
Warning: 2 possible package resolutions (only showing differing packages):
  - QuantStack::xeus-cling-0.4.10-vc14_0
  - quantstack::xeus-cling-0.4.10-vc14done

# All requested packages already installed.


(cling) C:\>

But I also do not see a C++ kernel under Jupiter notebook's "New" button, only Python option etc.
Could you please give your take on that what I may try to make it work?

Would highly appreciate it!

Thanks,
Rami

**Comment by martinRenou** [comment]
As said two comments over your comment, we do not support windows yet.

**Comment by yopuedoiralbano** [comment]
> As said two comments over your comment, we do not support windows yet.

Any update on this, do you have windows support now????

**Comment by SylvainCorlay** [comment]
@yopuedoiralbano we are mostly blocked on upstream issue https://github.com/root-project/cling/issues/300.

If you are an expert, we need help with this!
