### ISSUE TITLE
what is the requirement for llvm to compile xeus-cling

### ISSUE THREAD

**Issue by j2innet** [QuantStack/xeus-cling#266]
i build from source all done except xeus-cling
compile xeus-cling stuck in llvm config
my llvm-config is 3.4
thanks in advance

below is the error i get. 

>>>

-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building xeus-cling v0.7.1
-- Found LLVM_CONFIG as /usr/bin/llvm-config
usage: llvm-config <OPTION>... [<COMPONENT>...]

Get various configuration information needed to compile programs which use
LLVM.  Typically called from 'configure' scripts.  Examples:
  llvm-config --cxxflags
  llvm-config --ldflags
  llvm-config --libs engine bcreader scalaropts

Options:
  --version         Print LLVM version.
  --prefix          Print the installation prefix.
  --src-root        Print the source root LLVM was built from.
  --obj-root        Print the object root used to build LLVM.
  --bindir          Directory containing LLVM executables.
  --includedir      Directory containing LLVM headers.
  --libdir          Directory containing LLVM libraries.
  --cppflags        C preprocessor flags for files that include LLVM headers.
  --cflags          C compiler flags for files that include LLVM headers.
  --cxxflags        C++ compiler flags for files that include LLVM headers.
  --ldflags         Print Linker flags.
  --libs            Libraries needed to link against LLVM components.
  --libnames        Bare library names for in-tree builds.
  --libfiles        Fully qualified library filenames for makefile depends.
  --components      List of all possible components.
  --targets-built   List of all targets currently built.
  --host-target     Target triple used to configure LLVM.
  --build-mode      Print build mode of LLVM tree (e.g. Debug or Release).
Typical components:
  all               All LLVM libraries (default).
  engine            Either a native JIT or a bitcode interpreter.
-- /usr/bin/llvm-config --assertion-mode --bindir --libdir --includedir --prefix --src-root
CMake Error at CMakeLists.txt:73 (message):
  llvm-config failed with status 1

-- Configuring incomplete, errors occurred!

SOLVED

i do this, 

from venv
install cling in miniconda
jupyter kernelspec install --user .conda/envs/cling/share/jupyter/kernels/xeus-cling-cpp11
conda deactivate cling
still within venv
jupyter kernelspec list
Available kernels:
  xcpp11     /home/foo/.local/share/jupyter/kernels/xcpp11
  xcpp14     /home/foo/.local/share/jupyter/kernels/xcpp14
  xcpp17     /home/foo/.local/share/jupyter/kernels/xcpp17
  python3    /home/foo/.virtualenvs/py3/share/jupyter/kernels/python3

jupyter lab

finally, 
python3 installed jupyter lab can see miniconda installed cling c++11 now.

**Comment by SylvainCorlay** [comment]
The required version is llvm 5.0.0!

Thanks
