### ISSUE TITLE
Error occurred when overloading operator

### ISSUE THREAD

**Issue by tommytim0515** [QuantStack/xeus-cling#269]
Thank you so much for bringing us such a fantastic tool!
Some errors occurred while doing operator overloading outside of the class:
```c++
using namespace std;
class Vector
{
    public:
        Vector(double a = 0, double b = 0) : x(a), y(b) {}
        double getx() const { return x; }
        double gety() const { return y; }
        void print() const { cout << "(" << x << " , " << y << ")\n"; }
    
        Vector operator+(const Vector& b)
        {
            return Vector(getx() + b.getx(), gety() + b.gety());
        }
    private:
        double x, y;
}
```
and 
```c++
Vector add(const Vector& a, const Vector& b)
{
    return Vector(a.getx() + b.getx(), a.gety() + b.gety());
}


Vector operator+(const Vector& a, const Vector& b)
{
    return Vector(a.getx() + b.getx(), a.gety() + b.gety());
}
```
The error was:
```
input_line_12:8:1: error: function definition is not allowed here
{
^
Interpreter Error: 
```

Currently, I am using xeus-cling installed from miniconda with 'conda install xeus-cling'.
My OS is Ubuntu 19.10. This issue also happened on my Windows WSL system, also Ubuntu.

**Comment by martinRenou** [comment]
I suppose it's coming from the fact you are defining mutliple functions in the **same cell**. The Cling interpreter does not seem to like that very much.

Try defining one function per cell, I hope this should work

**Comment by tommytim0515** [comment]
Thank you for your immediate response. After trying separating the function definitions, the error still exists.
![Screenshot from 2019-11-05 18-23-17](https://user-images.githubusercontent.com/44408451/68199630-5e90d380-fff9-11e9-9680-0f3be377daa2.png)

**Comment by JohanMabille** [comment]
Try putting the include statements in dedicated cells with no other cell. Then restart the kernel and reexecute the cells (when too many errors occu the kernel might becom instable and unable to compile code that is correct).

**Comment by tommytim0515** [comment]
After trying that, it seems the 
![Screenshot from 2019-11-05 18-39-43](https://user-images.githubusercontent.com/44408451/68200947-d65ffd80-fffb-11e9-86f9-f665b2e1a332.png)
error still exists.

**Comment by martinRenou** [comment]
This seems to be related to https://github.com/root-project/cling/issues/184...
