### ISSUE TITLE
New Xeus-Cling release

### ISSUE THREAD

**Issue by SimeonEhrig** [QuantStack/xeus-cling#279]
I'm really interested in a new version of Xeus-Cling with cling 0.6. I have seen that there is a patch for the new cling base in the master branch. When will the next version be ready?

Is this issue a showstopper for a new release? : https://github.com/root-project/cling/issues/325

**Comment by SylvainCorlay** [comment]
Hello @SimeonEhrig this is not a showstopper.
I am looking into the windows test failures before tagging a release!

**Comment by SimeonEhrig** [comment]
Okay, thanks for the answer.

**Comment by SylvainCorlay** [comment]
Hey @SimeonEhrig we have released xeus-cling 0.8.0!

We have not uploaded a windows conda package yet though. Other builds will be available for download in 30 - 40 min.

**Comment by SimeonEhrig** [comment]
Thank you for the reminder.

**Comment by SylvainCorlay** [comment]
Hey @SimeonEhrig we should connect sometimes to discuss future plans for cling, CUDA etc.

Would like to have a quick chat over video sometimes (today or later this week)?

**Comment by SimeonEhrig** [comment]
Sounds like a good idea. Unfortunately I'm very busy this week. Can we chat next week?

**Comment by SylvainCorlay** [comment]
Sure. Just drop me a line when you when is a good time!

**Comment by SimeonEhrig** [comment]
Monday afternoon or Tuesday would be good

**Comment by SylvainCorlay** [comment]
Hey @SimeonEhrig would you be available to chat this Monday afternoon?

**Comment by SimeonEhrig** [comment]
Yes, we can chat this Monday afternoon.
