### ISSUE TITLE
Not Showing OutPut

### ISSUE THREAD

**Issue by karthikone** [QuantStack/xeus-cling#280]
> OS Linux(Debian10), Google Chrome, Tried in **Firefox**,**Restarted kernels**, Installed through **Anaconda**,**Miniconda**,**pip** but no use. Showing errors but Not Showing the Outputs🤷.

**program :** 
>    include<iostream>
    using namespace std;

>  int main( )
    {
        cout<<"No output";
        return 0;
    }

![Screenshot from 2019-12-09 21-22-51](https://user-images.githubusercontent.com/37996713/70450648-14a07f00-1aca-11ea-8322-a26cd5b78f25.png)

**Comment by SylvainCorlay** [comment]
there is no need tor a main function!

**Comment by SylvainCorlay** [comment]
You can try the binder link in the readme to get an idea of how this works!
