### ISSUE TITLE
Distinction between output and result messages

### ISSUE THREAD

**Issue by nthiery** [QuantStack/xeus-cling#67]
Hi,
I just noticed with @takluyver that the xeus-cling output's are not prefixed with [Out ??] prompts:
```
In [1] 1 + 1
(int) 2
```
instead of
```
In [1] 1 + 1
Out[1] (int) 2
```

This suggests that the output messages are not tagged as "execute_result" as one would expect.

Potentially related: we noticed with @gouarin that nbgrader does not pick error messages when grading `xeux-cling` notebooks. @takluyver just mentionned that there are two types of error messages which is a [regular source of confusion between kernels and frontends](https://github.com/jupyter/enhancement-proposals/pull/24). Maybe that's what's happening here, with nbgrader expecting one type, and xeus-cling sending the other.

**Comment by SylvainCorlay** [comment]
In fact, the xeus library (implementing the protocol) supports both streaming `cout` and `cerr` to the front-end displaying execute results, which are the two types of outputs involved here

<img width="491" alt="screen shot 2017-10-17 at 9 28 27 pm" src="https://user-images.githubusercontent.com/2397974/31685172-5f379c30-b382-11e7-9b66-858eaa637de3.png">

But for the `xeus-cling` kernel, we don't use execute results. The reason is that we capture all the standard and error stream content, **including** the output, so we avoid the duplication by not using the returned value.

If we find a way in the API of the cling interpreter to get that content without it being sent to the standard output, we could have a behavior closer to the one of the python kernel.

**Comment by gouarin** [comment]
I think we can have the same behavior. The `execute_reply` will happen in `xeus-cling` only if the last line doesn't have a semicolon. 

And `cling` must be able to give us this information because the behavior is different if you have or you don't have this semicolon. If not, we can add a regexp to know if the last string followed by a semicolon or not.

Or I missed something ...

**Comment by SylvainCorlay** [comment]
I don't think you missed anything! 
Ideally, I would prefer not to rely on more regex parsing the code.
Ideally, the behavior should be configurable with the cling API.

**Comment by nthiery** [comment]
I just realized that this issue is very relevant for teaching. Grasping the distinction between printing and returning is one of the main difficulties for our beginning students. Anything that enhance visually the distinction will help. So a solution will be very welcome!
No rush though, since we won't be able to put a new xeus-cling version in production before the end of the semester.

**Comment by nthiery** [comment]
Any thoughts about the error message situation?

**Comment by SylvainCorlay** [comment]
> Any thoughts about the error message situation?

xeus-cling does not do much more about errors than printing into the error stream, which is redirected to the front-end (styled in red in the notebook).

Maybe @takluyver / @ivanov / @ellisonbg would have an opinion about this. We would be happy to follow a better practice.

Regarding the standard output stream versus execute reply, as detailed above, this was a workaround for the redirection of the standard output which also prints the returned value...

**Comment by takluyver** [comment]
Is it possible to detect whether execution caused an error or not? If so, it would be useful to send back an indication that the error occurred. There are currently two ways to do that, and we're just working out if it's possible to condense them down to one.

**Comment by SylvainCorlay** [comment]
Yes! we catch exception in the kernel layer. How would you like errors to be indicated in the messages (besides outputing things in the error stream).

**Comment by takluyver** [comment]
- [Error message](http://jupyter-client.readthedocs.io/en/latest/messaging.html#execution-errors) on IOPub.
- [Error fields](http://jupyter-client.readthedocs.io/en/latest/messaging.html#request-reply) in the execute_reply message on the shell channel.

It looks like we're not going to clean up the duplication, so it's best to send both.

**Comment by gouarin** [comment]
I looked at the `cling` source code. It seems difficult to have the information from `cling ` to know if the end of the last string line is a semicolon or not. It is internal stuff in cling interpreter.

@takluyver could you give two Python examples to illustrate the behavior of the error messages ? one for `Error message` and one for `Error fields`.

**Comment by SylvainCorlay** [comment]
> I looked at the cling source code. It seems difficult to have the information from cling to know if the end of the last string line is a semicolon or not. It is internal stuff in cling interpreter.

This is not really what I would like to do. Instead, I would just like to be able to disable the use of the standard output for execution results by cling, which would be cleaner.

**Comment by takluyver** [comment]
> could you give two Python examples to illustrate the behavior of the error messages ?

Here's an example in bash_kernel. The call to `send_response` sends the error message on IOPub, and the `return` value is the content which will become the `execute_reply` message.

https://github.com/takluyver/bash_kernel/blob/0966dc102d7549f5c909c93de633a95b2af9f707/bash_kernel/kernel.py#L163-L169

**Comment by SylvainCorlay** [comment]
It is not a problem to have exactly the same behavior as in IPython with xeus cling. The only thing issue is that with the current way we interact with cling, `(int) 2` would be printed twice, once without the `Out[]` prompt, then once with it. I would just like to disable the printing of this in the redirected standard output. Ideally, there would be no regex involved...

**Comment by gouarin** [comment]
@SylvainCorlay you're right. So the idea could be to add an output stream in the Value class of `cling` in order to specify the output when we call `Value::dump`. This is this function which adds the output of the last line without semicolon. The default value could be `cling::outs` and in `xeus-cling` we can change this output stream.

I can open an issue in `cling` if you are ok with this solution.

**Comment by gouarin** [comment]
https://github.com/root-project/cling/blob/master/lib/Interpreter/Interpreter.cpp#L1200

**Comment by SylvainCorlay** [comment]
cc @vgvassilev

**Comment by SylvainCorlay** [comment]
This is fixed in master.

**Comment by SylvainCorlay** [comment]
@takluyver @nthiery we released xeus-cling `0.2.0` with this issue fixed.

We also support displaying rich output as per example:

<img width="747" alt="screen shot 2018-03-04 at 2 30 12 am" src="https://user-images.githubusercontent.com/2397974/36941133-1d19b98a-1f54-11e8-983c-5569433d0f5c.png">

Check out the binder!

**Comment by nthiery** [comment]
Yippee! Thanks!
I am looking forward trying this out, and in particular checking whether this solves our issue with nbgrader.

**Comment by SylvainCorlay** [comment]
I am really excited about rich rendering of outputs. Beyond widgets and images, we can display arbittary mime types for which we have a renderer in jupyterlab or the classic notebook...

**Comment by SylvainCorlay** [comment]
Quick example with an audio file:

<img width="740" alt="screen shot 2018-03-04 at 10 16 14 pm" src="https://user-images.githubusercontent.com/2397974/36950669-b7c347c6-1ff9-11e8-8eed-93f4d0f10918.png">

**Comment by nthiery** [comment]
I just tested xeus-cling 0.2.2, and can confirm that `nbgrader` now works properly.

Steps to reproduce:
- conda install nbgrader
- load this notebook: [test-nbgrader-cling.ipynb.gz](https://github.com/QuantStack/xeus-cling/files/1793562/test-nbgrader-cling.ipynb.gz)
- click on validate
Thanks!

Watch out students, gonna grade you :-)

**Comment by wolfv** [comment]
We should also update `xtensor-io` demo notebooks at some point :)
