### ISSUE TITLE
Failing to load a dynamic library that loads in plain cling

### ISSUE THREAD

**Issue by nthiery** [QuantStack/xeus-cling#71]
I am trying to load a dynamic library, and am getting a failure:
![image](https://user-images.githubusercontent.com/545328/31963810-43019554-b902-11e7-9264-f915bef4473f.png)

The same commands work with plain cling from the same conda environment, in the same directory.
MLV is from debian package libmlv0-dev. One thing that may have an influence is that MLV.h is not in the system dir but in the same directory as the notebook. In any cases, the error message looks dubious.

I could try with other libraries if useful.

**Comment by SylvainCorlay** [comment]
The `dot` versiobs of the cling commands don't work with the kernel. 

Instead, you can use the cling pragmas 

For loading a library, use

```
#pragma cling load
```

Which is also more c++ compliant. Examples available in xtensor-blas.

**Comment by nthiery** [comment]
That worked! Perfect. Thanks a lot Sylvain.
Micro suggestion: could the `dot` version of the cling commands raise an explicit error in the kernel, suggesting to use the pragma as you just did?

**Comment by SylvainCorlay** [comment]
OK, closing and opening a separate issue for the warning.
