### ISSUE TITLE
failed to start on miniconda3

### ISSUE THREAD

**Issue by laoshaw** [QuantStack/xeus-cling#76]
on Ubuntu 16.04 64bit I did the standard conda installation(the 3 steps conda install at the homepage here), when I run 'jupyter notebook" I got a backtrace:
/home/xx/miniconda3/compiler_compat/ld: cannot find -lpthread
/home/xx/miniconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/xx/miniconda3/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/xx/miniconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/xx/miniconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory

Note, this is not a fresh new miniconda3, the existing packages are:
# packages in environment at /home/xx/miniconda3:
#
asn1crypto                0.22.0           py36h265ca7c_1  
bash_kernel               0.7.1                     <pip>
bleach                    2.0.0            py36h688b259_0  
ca-certificates           2017.08.26           h1d4fec5_0  
certifi                   2017.7.27.1      py36h8b7b77e_0  
cffi                      1.10.0           py36had8d393_1  
chardet                   3.0.4            py36h0f667ec_1  
clangdev                  3.9.1                   cling_5  [cling]  QuantStack
cling                     0.3.post2               cling_4  [cling]  QuantStack
cling-patches             1                             0    QuantStack
conda                     4.3.30           py36h5d9f9f4_0  
conda-env                 2.6.0                         0    conda-forge
cppzmq                    4.2.1                         0    QuantStack
cryptography              2.0.3            py36ha225213_1  
cryptopp                  5.6.5                         3    QuantStack
cycler                    0.10.0           py36h93f1223_0  
dbus                      1.10.22              h3b5a359_0  
decorator                 4.1.2            py36hd076ac8_0  
entrypoints               0.2.3            py36h1aec115_2  
expat                     2.2.4                h6ea4f2b_2  
fontconfig                2.12.4               h88586e7_1  
freetype                  2.8                  h52ed37b_0  
gcc-6                     6.1.0                         0    QuantStack
glib                      2.53.6               hc861d11_1  
gmp                       6.1.2                hb3b607b_0  
gst-plugins-base          1.12.2               he3457e5_0  
gstreamer                 1.12.2               h4f93127_0  
html5lib                  0.999999999      py36h2cfc398_0  
icu                       58.2                 h211956c_0  
idna                      2.6              py36h82fb2a8_1  
intel-openmp              2018.0.0             h15fc484_7  
ipykernel                 4.6.1            py36hbf841aa_0  
ipython                   6.1.0            py36hc72a948_1  
ipython_genutils          0.2.0            py36hb52b0d5_0  
ipywidgets                7.0.0            py36h7b55c3a_0  
isl                       0.16.1                        0    QuantStack
jedi                      0.10.2           py36h552def0_0  
jinja2                    2.9.6            py36h489bce4_1  
jpeg                      9b                   h376031c_1  
jsonschema                2.6.0            py36h006f8b5_0  
jupyter                   1.0.0            py36h9896ce5_0  
jupyter_client            5.1.0            py36h614e9ea_0  
jupyter_console           5.2.0            py36he59e554_1  
jupyter_core              4.3.0            py36h357a921_0  
libcxx                    3.9.1                         0    QuantStack
libedit                   3.1                  heed3624_0  
libffi                    3.2.1                h4deb6c0_3  
libgcc-6                  6.2.0                         2    QuantStack
libgcc-ng                 7.2.0                h7cc24e2_2  
libgfortran-ng            7.2.0                h9f7466a_2  
libpng                    1.6.32               hda9c8bc_2  
libsodium                 1.0.13               h31c71d8_2  
libstdcxx-ng              7.2.0                h7a57d05_2  
libxcb                    1.12                 h84ff03f_3  
libxml2                   2.9.4                h6b072ca_5  
llvmdev                   3.9.1                   cling_5  [cling]  QuantStack
markupsafe                1.0              py36hd9260cd_1  
matplotlib                2.1.0            py36hba5de38_0  
mistune                   0.7.4            py36hbab8784_0  
mkl                       2018.0.0             hb491cac_4  
mpc                       1.0.3                         4    QuantStack
mpfr                      3.1.5                         0    QuantStack
nbconvert                 5.3.1            py36hb41ffb7_0  
nbformat                  4.4.0            py36h31c9010_0  
ncurses                   6.0                  h06874d7_1  
notebook                  5.2.2                    py36_0    conda-forge
numpy                     1.13.3           py36ha12f23b_0  
openssl                   1.0.2l               h077ae2c_5  
pandas                    0.20.3           py36h842e28d_2  
pandoc                    1.19.2.1             hea2e7c5_1  
pandocfilters             1.4.2            py36ha6701b7_1  
patsy                     0.4.1            py36ha3be15e_0  
pcre                      8.41                 hc71a17e_0  
pexpect                   4.2.1            py36h3b9d41b_0  
pickleshare               0.7.4            py36h63277f8_0  
pip                       9.0.1            py36h8ec8b28_3  
prompt_toolkit            1.0.15           py36h17d85b1_0  
ptyprocess                0.5.2            py36h69acd42_0  
pycosat                   0.6.2            py36h1a0ea17_1  
pycparser                 2.18             py36hf9f622e_1  
pygments                  2.2.0            py36h0d3125c_0  
pyopenssl                 17.2.0           py36h5cc804b_0  
pyparsing                 2.2.0            py36hee85983_1  
pyqt                      5.6.0            py36h0386399_5  
pysocks                   1.6.7            py36hd97a5b1_1  
python                    3.6.3                hc9025b9_1  
python-dateutil           2.6.1            py36h88d3b88_1  
pytz                      2017.2           py36hc2ccc2a_1  
pyzmq                     16.0.2           py36h3b0cf96_2  
qt                        5.6.2               h974d657_12  
qtconsole                 4.3.1            py36h8f73b5b_0  
readline                  7.0                  hac23ff0_3  
redis-kernel              0.5.2                     <pip>
requests                  2.18.4           py36he2e5f8d_1  
ruamel_yaml               0.11.14          py36ha2fb22d_2  
scikit-learn              0.19.1           py36h7aa7ec6_0  
scipy                     0.19.1           py36h9976243_3  
seaborn                   0.8.0            py36h197244f_0  
setuptools                36.5.0           py36he42e2e1_0  
simplegeneric             0.8.1            py36h2cb9092_0  
sip                       4.18.1           py36h51ed4ed_2  
six                       1.10.0           py36hcac75e4_1  
sqlite                    3.20.1               h6d8b0f3_1  
statsmodels               0.8.0            py36h8533d0b_0  
system                    5.8                           2    QuantStack
terminado                 0.6              py36ha25a19f_0  
testpath                  0.3.1            py36h8cadb63_0  
tk                        8.6.7                h5979e9b_1  
tornado                   4.5.2            py36h1283b2a_0  
traitlets                 4.3.2            py36h674d592_0  
urllib3                   1.22             py36hbe7ace6_0  
util-linux                2.21                          0    QuantStack
wcwidth                   0.1.7            py36hdf4376a_0  
webencodings              0.5.1            py36h800622e_1  
wheel                     0.29.0           py36he7f4e38_1  
widgetsnbextension        3.0.2            py36hd01bb71_1  
xeus                      0.8.0                         0    QuantStack
xeus-cling                0.0.7                         0    QuantStack
xtl                       0.3.6                         0    QuantStack
xz                        5.2.3                h2bcbf08_1  
yaml                      0.1.7                h96e3832_1  
zeromq                    4.2.1                         1    QuantStack
zlib                      1.2.11               hfbfcf68_1

**Comment by gouarin** [comment]
Could you try in a fresh conda environment ?

Like

```
conda create -n cling
source activate cling
conda install xeus-cling ....
```

and tell us if it works.


2017-11-29 20:23 GMT+01:00 laoshaw <notifications@github.com>:

**Comment by laoshaw** [comment]
yes a fresh env works fine. Thanks!
