### ISSUE TITLE
PackageNotFoundError in windows

### ISSUE THREAD

**Issue by protik77** [QuantStack/xeus-cling#77]
I am trying to install `xeus-cling` following the installation instruction in a Windows machine. The first step went well. But the second command returns a `PackageNotFoundError`. The output looks like:

```
conda install xeus-cling -c QuantStack -c conda-forge
Fetching package metadata .................

PackageNotFoundError: Packages missing in current channels:

  - xeus-cling

We have searched for the packages in the following channels:

  - https://conda.anaconda.org/QuantStack/win-64
  - https://conda.anaconda.org/QuantStack/noarch
  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.continuum.io/pkgs/main/win-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/win-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/win-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/win-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://repo.continuum.io/pkgs/msys2/win-64
  - https://repo.continuum.io/pkgs/msys2/noarch
````

Is this package unavailable for Windows or it is not updated yet?

**Comment by gouarin** [comment]
At the moment, `xeus-cling` is not well packaging for Windows.

I am working on the Windows packaging using conda and you should have a working installation soon.

**Comment by momonala** [comment]
Please tell us when its out! Really looking forward to using this tool.

**Comment by SylvainCorlay** [comment]
@momonala you can already try it online by clicking on the `launch binder` badge in the readme.

**Comment by momonala** [comment]
@SylvainCorlay  Very cool. Thanks!

**Comment by protik77** [comment]
@gouarin I see. Looking forward to use it in my machine.

Also, please clarify the information in the README to avoid redundancy of the same issue.

**Comment by gouarin** [comment]
@protik77  @momonala `xeus-cling` is now available on windows 64.

You need to install a fresh miniconda environment 

```
conda create -n cling
source activate cling
```

And then install `xeus-cling`

```
conda install xeus-cling -c gouarin -c conda-forge
conda install notebook -c conda-forge
```

The conda channel `gouarin` is provisional and should change to `QuantStack` in the next few days.

I don't test this version because I don't have windows. So tell me if it doesn't work.

**Comment by momonala** [comment]
@gouarin  after installing with those commands and running Jupyter I get no option for starting a C++ notebook

**Comment by wukongtea** [comment]
@gouarin  thank you so much, you may use ( activate cling )  in windows.
![image](https://user-images.githubusercontent.com/25115961/33490494-5cd7edf8-d6f2-11e7-9847-cbe1b50cf842.png)
![image](https://user-images.githubusercontent.com/25115961/33490524-72085348-d6f2-11e7-9fbd-1817d271ef33.png)
![image](https://user-images.githubusercontent.com/25115961/33490531-77ba3fea-d6f2-11e7-8303-567d8da71f95.png)
it doesnt work in jupyter book?

**Comment by SylvainCorlay** [comment]
@momonala @wukongtea please bare with us. This is work in progress and should be solved shortly :)

**Comment by gouarin** [comment]
The first issue was to move the directory /Library/share/jupyter into /share/jupyter in your environment.

You will ba able to start a C++ notebook. But there are other issues ...

**Comment by momonala** [comment]
@SylvainCorlay no problem. I'm able to use it in MyBinder or in a Linux VM. Its great so far. Looking forward to the Windows release!

**Comment by wukongtea** [comment]
@SylvainCorlay  ok,than you. the present work is meaningful。

**Comment by meowklaski** [comment]
FYI to Windows 10 users: xeus-cling works like a charm in Windows Subsystem for Linux. I just followed the README instructions exactly - no fuss.

**Comment by isaac34mi** [comment]
any updates on the windows release ? Thks

**Comment by JohanMabille** [comment]
We need to compile every dependencies of xeus-cling with the same compiler / runtime and are currently facing issues with the compilation of libzmq. This may take some time to fix.

**Comment by ivorne** [comment]
I have problem that exactly matches this description. I am trying to install xeus-cling on win64 from channel QuantStack. The channel is in channel list and Anaconda Navigator lists xeus-cling in available packages. When tryig to install it (either from Anaconda Navigator or using command conda), it will fail with PackageNotFoundError (the same message as in original poster protik77 reported).

Was this issue resolved somehow or is there still the same problem? Thks.

**Comment by vbillet** [comment]
Exactly same issue. Meanwhile, I think I have some progress : 
I Did the following steps : 
````
conda create -n cling
conda activate cling

conda install -c conda-forge xeus
conda install -c conda-forge xtl
conda install -c conda-forge cling
conda install -c quantstack pugixml
conda install -c conda-forge cxxopts 
conda install -c conda-forge nlohmann_json
conda install -c conda-forge dirent
````
I copied manually files needed in Kernel directory. I also updated json files which were pointing to a **bld** directory
Then I managed to copy the following files in a single directory : 
````
17/05/2019  10:38               290 a.json
29/01/2019  17:33        16 008 704 c-index-test.exe
29/01/2019  17:34        56 568 320 clang++.exe
29/01/2019  17:33        46 287 872 clang-check.exe
29/01/2019  17:34        56 568 320 clang-cl.exe
29/01/2019  17:34        56 568 320 clang-cpp.exe
29/01/2019  17:31         2 082 304 clang-format.exe
29/01/2019  17:31        17 047 040 clang-import-test.exe
29/01/2019  17:31         2 301 440 clang-offload-bundler.exe
29/01/2019  17:33        14 106 112 clang-rename.exe
29/01/2019  17:31        56 568 320 clang.exe
17/05/2019  11:14    <DIR>          cling
15/06/2017  02:54            21 791 git-clang-format
29/01/2019  17:33        44 388 352 libclang.dll
28/06/2018  14:00         2 483 360 libcrypto-1_1-x64.dll
23/04/2019  11:50           324 608 libxeus.dll
13/01/2019  09:34           488 448 libzmq-mt-4_3_1.dll
01/08/2016  10:04            53 444 scan-build
13/11/2015  22:34                23 scan-build.bat
21/12/2015  14:19             4 504 scan-view
17/05/2019  12:55                20 test.cpp
13/12/2018  02:30        52 711 424 xeus-cling.exe
````

But now I have the following error : 
````
C:\Work\notebooks\xeus-cling>xeus-cling.exe -f a.json -std=c++14
2
2
2
2
2
2
2
2
2
ERROR in cling::CIFactory::createCI():
  resource directory C:/bld/xeus-cling_1544660831115/_b_env/Library\lib\clang\5.0.0 not found!
In file included from input_line_1:1:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\new:6:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\exception:7:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\yvals.h:7:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include\yvals_core.h:334:2: error: STL1000: Unexpected compiler version, expected Clang 7 or newer.
#error STL1000: Unexpected compiler version, expected Clang 7 or newer.
 ^

````
and my a.json file is like this : 
````
{
  "shell_port": 53830,
  "iopub_port": 53831,
  "stdin_port": 53832,
  "control_port": 53833,
  "hb_port": 53834,
  "ip": "127.0.0.1",
  "key": "cd4de843-1d7f906b4112481fa3d7134c",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": "xeus-cling-cpp11"
}
````

and Jupyter console seems to stop here : 
````
[I 13:55:36.463 NotebookApp] Creating new notebook in
[E 13:55:38.534 NotebookApp] Failed to run command:
    ['C:/bld/xeus-cling_1544660831115/_b_env/Library/bin/xeus-cling', '-f', 'C:\\Users\\vbill\\AppData\\Roaming\\jupyter\\runtime\\kernel-c167ad61-fb89-4ae1-bf45-96dc3f9402da.json', '-std=c++14']
````
I Have no bld directory on my PC.

Any Ideas ?

**Comment by SylvainCorlay** [comment]
@vbillet 

- cling 0.5 does no.t work properly on windows
- the prefered way of installing cling / xeus-cling is from the conda-forge channel, which does not provide a windows build
- the QuantStack channel which had a windows build is deprecated, and only holds an old version.

Installing on linux, or docker from conda-forge, or on OS X is the way forward.

**Comment by mustafaabbs2** [comment]
I still have problems installing xeus-cling. Was this issue resolved?

**Comment by SylvainCorlay** [comment]
@mustafaabbs2 windows is not supported.

**Comment by WesFrank** [comment]
Best bet is to use Windows Subsystem for Linux, as mentioned by @ghost "FYI to Windows 10 users: xeus-cling works like a charm in Windows Subsystem for Linux. I just followed the README instructions exactly - no fuss."

However, this comes with some other problems. For one "#pragma cling load(<library_name>)" to import .dll or .lib files won't work, as far as I know, probably because it's not windows-compatible. It only works for .a and .so.

Is there a solution for this yet?
