### ISSUE TITLE
Destroyed root environment

### ISSUE THREAD

**Issue by hfarazi** [QuantStack/xeus-cling#81]
I destroyed my root environment by doing:
`conda install cling -c QuantStack -c conda-forge`
`conda install xeus-cling -c QuantStack -c conda-forge`
`conda install notebook -c conda-forge`

Now I cannot use my jupyter notebook anymore: [https://github.com/QuantStack/xeus-cling/issues/79](https://github.com/QuantStack/xeus-cling/issues/79)

How can I undo it?

**Comment by SylvainCorlay** [comment]
`conda update libzmq -c conda-forge` should get you the libzmq build from conda-forge

**Comment by hfarazi** [comment]
hafez@hafez-pc:~$ conda update libzmq -c conda-forge
It did not work:

PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/hafez/anaconda3/envs/cling
  package name: libzmq

**Comment by SylvainCorlay** [comment]
my bad, the name of the package is zeromq.

**Comment by SylvainCorlay** [comment]
Closing the issue. Although feel free to continue the conversation here.

**Comment by hfarazi** [comment]
It did not solve the problem:

hafez@hafez-pc:~$ conda update zeromq -c conda-forge
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/hafez/anaconda3/envs/cling:

The following packages will be SUPERSEDED by a higher-priority channel:

    zeromq: 4.2.1-1 QuantStack --> 4.2.1-1 conda-forge

Proceed ([y]/n)?

zeromq-4.2.1-1 100% |######################################################################################################################| Time: 0:00:00 919.82 kB/s

afez@hafez-pc:~$ BS
hafez@hafez-pc:~$ jupyter notebook
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/hafez/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory

**Comment by hfarazi** [comment]
I suggest that instead of closing the issue and assume it will be solved, wait for the response.

**Comment by SylvainCorlay** [comment]
I invited you to continue the conversation should you have any issue - and I am still helping you.

Now on the technical side. it is an issue with a mix of channels. If you were using the default channel, you can try getting `pyzmq` and `zeromq` from it.

**Comment by hfarazi** [comment]
Ok thnx.
Nope, still broken:
`hafez@hafez-pc:~$ conda update zeromq -c conda-forge
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/hafez/anaconda3/envs/cling:
#
zeromq                    4.2.1                         1    conda-forge
hafez@hafez-pc:~$ conda install pyzmq -c conda-forge
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/hafez/anaconda3/envs/cling:
#
pyzmq                     16.0.2                   py36_2    conda-forge
hafez@hafez-pc:~$ conda update pyzmq -c conda-forge
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/hafez/anaconda3/envs/cling:
#
pyzmq                     16.0.2                   py36_2    conda-forge
hafez@hafez-pc:~$ jupyter notebook
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lpthread
/home/hafez/anaconda3/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/hafez/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/hafez/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory`

**Comment by SylvainCorlay** [comment]
can you please dump the result of conda list here? (and use three backticks to make it looks nicer)

**Comment by hfarazi** [comment]
```
hafez@hafez-pc:~$ conda list
# packages in environment at /home/hafez/anaconda3/envs/cling:
#
bleach                    2.0.0                    py36_0    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2017.11.5                py36_0    conda-forge
clangdev                  3.9.1                   cling_5  [cling]  QuantStack
cling                     0.3.post2               cling_4  [cling]  QuantStack
cling-patches             1                             0    QuantStack
cppzmq                    4.2.1                         0    QuantStack
cryptopp                  5.6.5                         3    QuantStack
decorator                 4.1.2                    py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
gcc-6                     6.1.0                         0    QuantStack
gmp                       6.1.2                         0    QuantStack
html5lib                  0.999999999              py36_0    conda-forge
icu                       58.1                          1    QuantStack
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
isl                       0.16.1                        0    QuantStack
jedi                      0.10.2                   py36_0    conda-forge
jinja2                    2.9.6                    py36_0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_client            5.1.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libcxx                    3.9.1                         0    QuantStack
libgcc-6                  6.2.0                         2    QuantStack
libiconv                  1.14                          4    QuantStack
libsodium                 1.0.10                        0    QuantStack
libxml2                   2.9.4                         4    QuantStack
llvmdev                   3.9.1                   cling_5  [cling]  QuantStack
markupsafe                1.0                      py36_0    conda-forge
mistune                   0.8                      py36_0    conda-forge
mpc                       1.0.3                         4    QuantStack
mpfr                      3.1.5                         0    QuantStack
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.2.2                    py36_0    conda-forge
openssl                   1.0.2m                        0    conda-forge
pandoc                    2.0.3                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pexpect                   4.3.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
readline                  6.2                           0    conda-forge
setuptools                37.0.0                   py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
system                    5.8                           2    QuantStack
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   4.5.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
util-linux                2.21                          0    QuantStack
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xeus                      0.8.0                         0    QuantStack
xeus-cling                0.0.7                         0    QuantStack
xtl                       0.3.6                         0    QuantStack
xz                        5.2.3                         0    QuantStack
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    QuantStack
```

**Comment by hfarazi** [comment]
Never mind I reinstalled my anaconda!!

**Comment by SylvainCorlay** [comment]
thanks. I am a bit confused by what is going on. I checked the content of the conda-forge package for zeromq and it does contain the file it is complaining about.
