### ISSUE TITLE
Using third-party libraries

### ISSUE THREAD

**Issue by jmh992** [QuantStack/xeus-cling#87]
How do I tell the interpreter where to look for third party libraries?

I would like to use [armadillo](http://arma.sourceforge.net/).

**Comment by gouarin** [comment]
- If you want to add include path

`#pragma cling add_include_path("inc_directory")`

- If you want to add library path

`#pragma cling add_library_path("lib_directory")`

- If you want to load library

`#pragma cling load("libname")`

You can use all this commands in a code cell in Jupyter notebook.

**Comment by ax3l** [comment]
Is there also an equivalent pragma for the cling `.U` for unload?

**Comment by vishwesh5** [comment]
Hi!

Sorry for commenting on an old post but my query concerns this only. I am trying to run OpenCV libraries using `xeus-cling`, and this is what I have done so far:
```
#pragma cling add_include_path("/home/ubuntu/installation/installation/OpenCV-3.4.1/include/")
#pragma cling add_library_path("/home/ubuntu/installation/installation/OpenCV-3.4.1/lib/")
```
```
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
int test2()
{
    std::cout << "Hello world!" << std::endl;
    cv::Mat image;
    return 0;
}
```
```
int retValue = test2();
```
I end up getting the following error:
```
IncrementalExecutor::executeFunction: symbol '_ZN2cv8fastFreeEPv' unresolved while linking [cling interface function]!
You are probably missing the definition of cv::fastFree(void*)
Maybe you need to load the corresponding shared library?
IncrementalExecutor::executeFunction: symbol '_ZN2cv3Mat10deallocateEv' unresolved while linking [cling interface function]!
You are probably missing the definition of cv::Mat::deallocate()
Maybe you need to load the corresponding shared library?
```
Can you please help me out with this?
Thanks in advance

**Comment by SylvainCorlay** [comment]
@vishwesh5 you are missing the `#pragma cling load('the_runtime_of_opencv')` to actually load the shared library.

In `xtensor` / `xtensor-blas`, we tend to include these pragmas in the headers of the libraries in question.

**Comment by vishwesh5** [comment]
Thank you @SylvainCorlay for the reply. But if I have to load these libraries, do I have to load all the `.so` files? Or is it something really trivial that I am missing?

**Comment by SylvainCorlay** [comment]
Probably not second-degree dependencies. You don't need to specify the `.so` extension.

**Comment by vishwesh5** [comment]
I guess I can understand what you are talking about, this is what we do in `OpenCV_libs.jl`:
```
# Loading config for OpenCV 3.4.1 shared libraries (.dylib, .so)
# Supports OSX (10.12.3) and Linux
# see README for details

cvlibdir = "/home/ubuntu/installation/installation/OpenCV-3.4.1/lib/"
cvheaderdir = "/home/ubuntu/installation/installation/OpenCV-3.4.1/include/"

version = "3.4.1"

libprefix = "libopencv_"

libNames = [
              "shape",
              "stitching",
              "objdetect",
              "superres",
              "videostab",
              "calib3d",
              "features2d",
              "highgui",
              "videoio",
              "imgcodecs",
              "video",
              "photo",
              "ml",
              "imgproc",
              "dnn",
              #"flann",   // TODO: resolve typeid error due to rtti flag
              "viz"
            ]

function getFullLibNames()
    return map(x -> "$(libprefix)$(x).$(version)", libNames)
end
```
So, even here, do we have to `load` all the `libopencv_<something>.3.4.1` libraries? I can write a Python script to get all such names. But I just want to make sure that this is what I have to do.

**Comment by SylvainCorlay** [comment]
I think that would be right. You might want to put this into some header file.

And for the longer term, suggest upstream that it gets included into the OpenCV C++ code base?

**Comment by vishwesh5** [comment]
For the header file, you mean that all the `#pragma cling load` should get in some let's say `loadLibraries.hpp` file?

**Comment by SylvainCorlay** [comment]
In `xtensor-blas`, there is a header included by all headers containing these statements for the BLAS runtime.

The header is in fact generated with cmake:

https://github.com/QuantStack/xtensor-blas/blob/master/include/xtensor-blas/xblas_config_cling.hpp.in

Only included in the case of cling so that the header-only package can still be used without having to use cmake:

https://github.com/QuantStack/xtensor-blas/blob/master/include/xtensor-blas/xblas_config.hpp

**Comment by vishwesh5** [comment]
Woah :open_mouth: ! Well I don't think there's something similar to this in `OpenCV`. I guess I will use Python to write such a header file and import it.
One more question. Let's say I create such a header file (`loadLibraries.hpp`) which has statements like these: `#pragma cling load` etc. etc.
Can I directly include it like `#include "loadLibraries.hpp"` if this file is present in the same directory? Or do I have to do `add_include_path`?

**Comment by vishwesh5** [comment]
Also, the `libname` that we supply in `#pragma cling load`, is it just the name or the complete path as well?

**Comment by SylvainCorlay** [comment]
Just the name. The search path is set in the `add_library_path` pragma.

**Comment by vishwesh5** [comment]
Thank you @SylvainCorlay. This is what I have stored in my `loadLibraries.h`:

```
#pragma cling load("libopencv_shape.3.4.1")
#pragma cling load("libopencv_stitching.3.4.1")
#pragma cling load("libopencv_objdetect.3.4.1")
#pragma cling load("libopencv_superres.3.4.1")
#pragma cling load("libopencv_videostab.3.4.1")
#pragma cling load("libopencv_calib3d.3.4.1")
#pragma cling load("libopencv_features2d.3.4.1")
#pragma cling load("libopencv_highgui.3.4.1")
#pragma cling load("libopencv_videoio.3.4.1")
#pragma cling load("libopencv_imgcodecs.3.4.1")
#pragma cling load("libopencv_video.3.4.1")
#pragma cling load("libopencv_photo.3.4.1")
#pragma cling load("libopencv_ml.3.4.1")
#pragma cling load("libopencv_imgproc.3.4.1")
#pragma cling load("libopencv_dnn.3.4.1")
#pragma cling load("libopencv_viz.3.4.1")
```
Is this right?

**Comment by ihnorton** [comment]
Wishing/spitballing here: it would be nice to be able to point xeus-cling at a `build.ninja`, or something like `compile_commands.json` (currently lacks linker info), and have imports just work*.

* modulo the pain suffered to make it work, of course.

**Comment by SylvainCorlay** [comment]
Yeah, so much to do!

**Comment by gzmp** [comment]
How would you reference

> * If you want to add include path
> 
> `#pragma cling add_include_path("inc_directory")`
> 
> * If you want to add library path
> 
> `#pragma cling add_library_path("lib_directory")`
> 
> * If you want to load library
> 
> `#pragma cling load("libname")`
> 
> You can use all this commands in a code cell in Jupyter notebook.

How would you include `boost/bind.hpp` this way? I've tried several variations, but unfortunately none of them seem to work because `boost/bind.hpp` includes `boost/bind/bind.hpp`. I've tried adding `/my/path/to/boost/bind/` as an include path, and some other variations, but it didn't help. Any idea what I can do?

**Comment by SylvainCorlay** [comment]
If you installed boost in some `PREFIX` directory, 

```
#pragma cling add_include_path("PREFIX/include")
```

results in:

```
#include <boost/bind.hpp>       // PREFIX/include/boost/bind.hpp
#include <boost/bind/bind.hpp>  // PREFIX/include/boost/bind/bind.hpp
```

**Comment by wolfv** [comment]
How about adding the info in here to the readme? @gouarin

**Comment by ax3l** [comment]
Related observation: It seams that the path `$(dirname $(which cling))/../include` is per default searched for includes, but the path `$(dirname $(which cling))/../lib` is not searched for equivalent shared library loads.

Can we add the latter for convenience, e.g. in conda-forge, by adding a default `-L` parameter to all kernels?

**Comment by SylvainCorlay** [comment]
@ax3l Sounds like a good idea!

**Comment by SimeonEhrig** [comment]
@ax3l 
By default, Cling use the content of `LD_LIBRARY_PATH` [1] and some systems paths like `/lib` and
`/usr/lib` as library paths at start.

[1]
- on Apple: `DYLD_LIBRARY_PATH` and `DYLD_FALLBACK_LIBRARY_PATH`
- on Windows: `PATH`

**Comment by ax3l** [comment]
Thanks for the notes!

For at least conda-forge, `LD_LIBRARY_PATH` is intentionally not set on user environments (I guess to avoid even more interaction with system-wide libs). Shall we patch the [kernel.json](https://github.com/jupyter-xeus/xeus-cling/blob/9fb4a92beefb861e9513498a9456a1435c59d153/share/jupyter/kernels/xcpp17/kernel.json.in) files for the [`xeus-cling-feedstock`](https://github.com/conda-forge/xeus-cling-feedstock)? I see #169 comes in handy again :D

**Comment by xgdgsc** [comment]
Is it possible to "unload" a library for now? I have some libraries I build myself that might change frequently. Is it possible to implement something like julia's `Revise.jl` ?

**Comment by aGIToz** [comment]
If you install opencv via conda, this puts the opencv header files and libraries inside your cling environment.
I was able to run this :
![image](https://user-images.githubusercontent.com/38216671/118440282-baa4df80-b6e7-11eb-817a-992efbaba692.png)
