### ISSUE TITLE
PackageNotFoundError MacOS

### ISSUE THREAD

**Issue by idotamir516** [QuantStack/xeus-cling#88]
I attempted to download -xeus-cling using both the commands 

> conda install -c quantstack xeus-cling

and

> conda install xeus-cling -c QuantStack -c conda-forge

Both of these resulted in the following output:

> Fetching package metadata .............
PackageNotFoundError: Packages missing in current channels:
 xeus-cling
We have searched for the packages in the following channels:
 https://conda.anaconda.org/quantstack/osx-64
 https://conda.anaconda.org/quantstack/noarch
 https://repo.continuum.io/pkgs/main/osx-64
 https://repo.continuum.io/pkgs/main/noarch
 https://repo.continuum.io/pkgs/free/osx-64
 https://repo.continuum.io/pkgs/free/noarch
 https://repo.continuum.io/pkgs/r/osx-64
 https://repo.continuum.io/pkgs/r/noarch
 https://repo.continuum.io/pkgs/pro/osx-64
 https://repo.continuum.io/pkgs/pro/noarch

What can I do to download xeus-cling successfully?

**Comment by gouarin** [comment]
@idotamir516 You need to use my channel

conda install xeus-cling -c gouarin -c conda-forge

We will move all the packages to the QuantStack channel soon.

**Comment by idotamir516** [comment]
Thank you that solved the problem
