### ISSUE TITLE
Can't define more than 1 function per cell 

### ISSUE THREAD

**Issue by momonala** [QuantStack/xeus-cling#89]
I get the error: `function definition is not allowed here` when I try to declare more than one function per cell. I was running C++14 on mybinder.org. Is there a work around?

![error](https://user-images.githubusercontent.com/16393105/33734658-6e881d94-db8d-11e7-9d74-03c9baab7c3b.png)

**Comment by gouarin** [comment]
This is a limitation of cling. We hope to solve this issue in a next release.

**Comment by momonala** [comment]
I see, no problem. Looking forward to the  new release.
