### ISSUE TITLE
Missing Functionality

### ISSUE THREAD

**Issue by idotamir516** [QuantStack/xeus-cling#90]
I have been trying to test out the '?' operator in terms of using it to search up classes on cppreference however it has not been working for any of the classes I have tried it on such as std::vector and std::string (I included them before using the '?' operator). The other functionality that isn't working is attempting to include any of the xwidgets. I used 

> #include "xwidgets/xbutton.hpp"

however it couldn't find the file. I am mentioning both of them here because it seems to me that maybe I didn't fulfill a dependency. The instructions I followed to download xeus-cling are those on the readme so if there is something that isn't on the readme that would enable this functionality that might be the reason.

**Comment by gouarin** [comment]
The '?' operator works on mac OS but it doesn't open a page at the bottom. We have to fix that. 
You can use the shift + Tab option which will open a pop up below the searched word with the right address. 

For your issue with xwidgets, did you install xwidgets ?

`conda install xwidgets -c gouarin -c conda-forge`
