### ISSUE TITLE
Cannot compile with cxxopts >= v2.0.0 

### ISSUE THREAD

**Issue by r9y9** [QuantStack/xeus-cling#92]
I'm trying to build xeus-cling from source and notice some dependency problem. With cxxopt https://github.com/jarro2783/cxxopts/ 

- master: build failed
- v2.0.0: build failed
- v1.4.4: build success

It would be great README mentions which versions of cxxopts are known to work as well as other dependencies (pugixml and cling, etc).

**Comment by SylvainCorlay** [comment]
Thanks @r9y9, good catch!
I was unaware of the cxxopts release, and we will look at what needs to be updated.

Feel free to open a PR adding a column for cxxopts in the dependency table.
